Install and import Numpy

In [10]:
%pip install numpy==2.4.4


Note: you may need to restart the kernel to use updated packages.


In [11]:
%pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

print(np.__version__)

2.4.4


Compare list and numpy array 

In [13]:
import time

n= 1_000_000

py_list = list(range(n))
np_array  = np.arange(n)


print(len(py_list))
print(len(np_array))

print(py_list[:10])
print(np_array[:10])

start = time.time()
py_res = [x*2 for x in py_list] 
end = time.time()
print(f"Python list took {end - start:.5f} seconds")

start = time.time()
np_res = np_array * 2   
end = time.time()
print(f"Numpy array took {end - start:.5f} seconds")


1000000
1000000
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
Python list took 0.05925 seconds
Numpy array took 0.00291 seconds


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [4,5,6]])
arr3 = np.array([[[4, 5, 6], [4,5,6]], [[4, 5, 6], [4,5,6]]])

print('\n1D Array:\n', arr1)
print(type(arr1))
print('\nShape of arr1:\n', arr1.shape)
print('\n2D Array\n', arr2)
print(type(arr2))
print('\nShape of arr2:\n', arr2.shape)


1D Array:
 [1 2 3]
<class 'numpy.ndarray'>

Shape of arr1:
 (3,)

2D Array
 [[4 5 6]
 [4 5 6]]
<class 'numpy.ndarray'>

Shape of arr2:
 (2, 3)


Array Attributes

In [17]:
print('\n3D Array\n', arr3)

print('Shape of arr1:', arr1.shape)
print('Shape of arr2:', arr2.shape)
print('Shape of arr3:', arr3.shape)

print('\n')

print('Number of dimensions of arr1:', arr1.ndim)
print('Number of dimensions of arr2:', arr2.ndim)  
print('Number of dimensions of arr3:', arr3.ndim)

print('\n')

print('Data type of arr1:', arr1.dtype)
print('Data type of arr2:', arr2.dtype)
print('Data type of arr3:', arr3.dtype)

print('Number of elements in arr1:', arr1.size)
print('Number of elements in arr2:', arr2.size)
print('Number of elements in arr3:', arr3.size)


3D Array
 [[[4 5 6]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]
Shape of arr1: (3,)
Shape of arr2: (2, 3)
Shape of arr3: (2, 2, 3)


Number of dimensions of arr1: 1
Number of dimensions of arr2: 2
Number of dimensions of arr3: 3


Data type of arr1: int64
Data type of arr2: int64
Data type of arr3: int64
Number of elements in arr1: 3
Number of elements in arr2: 6
Number of elements in arr3: 12


**Creating Special Arrays**

In [21]:
zeros = np.zeros((3, 3))
print('\n 3x3 array of zeros:\n', zeros)

ones = np.ones((4, 4))
print('\n 4x4 array of ones:\n', ones)

random_array = np.random.rand(3, 3)
print('\n 3x3 array of random numbers between 0 and 1:\n', random_array)

eye_matrix = np.eye(3)
print('\n 4x4 identity matrix:\n', eye_matrix)




 3x3 array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 4x4 array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 3x3 array of random numbers between 0 and 1:
 [[0.06135727 0.5287913  0.8294572 ]
 [0.64238318 0.32076565 0.49966659]
 [0.71687787 0.46253745 0.53690117]]

 4x4 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Example: Matrix multiplication with identity and zero matrices

import numpy as np

# Create a sample 2x2 matrix
A = np.array([[1, 2], [3, 4]])
print("Original matrix A:")
print(A)
print()

# Identity matrix multiplication (preserves A)
I = np.eye(2)
result_I = A @ I  # or np.dot(A, I)
print("A multiplied by identity matrix I:")
print(result_I)
print("Notice: A @ I = A (unchanged)")
print()

# Zero matrix multiplication (changes to all zeros)
Z = np.zeros((2, 2))
result_Z = A @ Z  # or np.dot(A, Z)
print("A multiplied by zero matrix Z:")
print(result_Z)
print("Notice: A @ Z = all zeros (changed)")